### ISSUE TITLE
Yoda Condition sniff not working on JavaScript files

### ISSUE THREAD

**Issue by darthvader666uk** [WordPress/WordPress-Coding-Standards#1168]
Hi,

Im using WordPress-Coding-Standards along with PHPCS so check my code while being submitting via Gitlab.  One of the check I use if Yoda Condition.  THis works perfectly within PHP files however, this doesnt seem to be the case for JavaScript files.

Is it possible to add this feature?

**Comment by dingo-d** [comment]
We're going to close this one because in PHPCS 4.0.0 the sniffer won't look at the JS and CSS files anymore, and today the tooling for the JS linting is separated from PHP lint tooling.

You can use the official [ESLint plugin](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-eslint-plugin/) to check your JS files.
