### ISSUE TITLE
Caching not being picked up by sniff for direct DB call

### ISSUE THREAD

**Issue by paulcanning** [WordPress/WordPress-Coding-Standards#1171]
I am having to use a direct DB call, due to `wp_query()` giving me odd results when combined with a second loop.

Below is my code:

```php
$latest_document_cached = wp_cache_get( 'latest_document' );

if ( false === $latest_document_cached ) {
	$latest_document = $wpdb->get_results( $wpdb->prepare( "
	    SELECT $wpdb->posts.* 
	    FROM $wpdb->posts
	    WHERE $wpdb->posts.post_status = %s 
	    AND $wpdb->posts.post_type = %s
	    ORDER BY $wpdb->posts.post_date DESC
	    LIMIT 1
	 ", 'publish', 'document' ), OBJECT ); // db call ok.

	wp_cache_set( 'latest_document', $latest_document );
} else {
	$latest_document = $latest_document_cached;
}
```

For whatever reason, PHPCS is still saying I need to use caching for my DB call, but as you can see, I am.

I am unable to find much documentation on using the WP_Cache object for DB calls, so it might be I'm missing something or got it in the wrong order?

**Comment by JDGrimes** [comment]
This works fine if the code is within a function. If it is within the file's global scope, then the sniff fails. The problem is that the sniff only looks for the caching function calls within the current function's scope, so when not inside one, it doesn't look for them. And since it didn't find them, of course, it gives the error.

I guess when not in a function's scope, the start and end of the file should be used as the endpoints to search for the caching functions within.

**Comment by jrfnl** [comment]
Walking a complete file to try and find a caching function call is pretty "expensive". Also, it will never be able to find caching calls made in the global scope in another file, so will always be imprecise.

I have confirmed what @JDGrimes wrote previously, that if the same code is being used within a function, the caching is picked up correctly.

So, the recommendation would be to use queries within a function rather than in the global namespace.
