### ISSUE TITLE
Add antispambot to list of functions that don't need escaping

### ISSUE THREAD

**Issue by Flimm** [WordPress/WordPress-Coding-Standards#1246]
The function `antispambot` takes an email address, and obfuscates it by encoding it using HTML entities. [Documentation](https://codex.wordpress.org/Function_Reference/antispambot)

For example, this code:

```php
echo antispambot( 'john.doe@mysite.com' );
```

This will output the email like this in the HTML:

```
&#106;&#111;h&#110;&#46;&#100;&#111;&#101;&#64;mysit&#101;.&#99;&#111;&#109;
```

PHPCS complains about that code, saying it should require escaping, when it doesn't.

**Comment by jrfnl** [comment]
Sounds like a function which should be added to the escaping list(s). Want to create a PR for this ?

**Comment by JDGrimes** [comment]
A close look at the code reveals that this function isn't actually safe. It does not encode the entire address, it randomly chooses whether to encode each individual character. So it is possible to pass HTML through it, and it will only be encoded part of the time, randomly.

However, in your example, there is no potential for XSS, because the value is hard-coded. So I think this function could be added to the [list of formatting functions](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/develop/WordPress/Sniff.php#L396-L419).

Then this would be recognized as safe:

```php
echo antispambot( 'john.doe@mysite.com' );
```

But this would still get flagged as needing escaping:


```php
echo antispambot( $email );
```

**Comment by Flimm** [comment]
Did you know that `esc_html` does not double-escape HTML?

```php
echo esc_html( 'test &amp; test' ); // prints test &amp; test
echo esc_attr( 'test &amp; test' ); // prints test &amp; test
```

So, therefore, using this code is safe and correct:

```php
echo esc_html( antispambot( $email ) );
```

I like @JDGrimes' idea of marking `antispambot` as a formatting function.

**Comment by jrfnl** [comment]
No idea why this wasn't ever actioned before, but PR #2145 should fix this now.
