### ISSUE TITLE
How to escape properly ?

### ISSUE THREAD

**Issue by jrfnl** [WordPress/WordPress-Coding-Standards#1270]
Just checking whether I've got this right. I intend to create a wiki page with the end results and/or get the handbooks improved and link to those from the wiki page.

I've indicated the areas where I'm not 100% sure that what I wrote is correct with :point_right:. Corrections on the other areas are of course welcome as well :sunglasses: 

### Any numeric variable used anywhere
```php
echo $int;
```
Depending on whether it is an integer or a float, `(int)`, `absint()`, `(float)` are all correct and acceptable.
At times, `number_format()` or `number_format_i18n()` might be more appropriate.

`intval()`, `floatval()` are acceptable, but are outdated (PHP4) functions.

### Arbitrary variable within HTML attribute
```php
echo '<div id="', $prefix, '-box', $id, '">';
```
This should be escaped with one call to `esc_attr()`.
When a variable is used as part of an attribute or url, it is always better to escape the whole string as that way a potential escape character just before the variable will be correctly escaped.

#### Correct:
```php
echo '<div id="', esc_attr( $prefix . '-box' . $id ), '">';
```

#### Incorrect:
```php
echo '<div id="', esc_attr( $prefix ), '-box', esc_attr( $id ), '">';
```

Note: nonces created using `wp_create_nonce()` should also be escaped like this if used in an HTML attribute.

### Arbitrary URL within HTML attribute, but also in other contexts
```php
echo '<a href="', $url, '">';
```
This should be escaped with `esc_url()`.

#### Correct:
```php
echo '<a href="', esc_url( $url ), '">';
```

#### Incorrect:
```php
echo '<a href="', esc_attr( $url ), '">';
echo '<a href="', esc_attr( esc_url( $url ) ), '">';
```

### Passing an arbitrary variable to javascript via `wp_localize_script()`
```php
wp_localize_script( 'handle', 'name',
	array(
		'prefix_nonce' => wp_create_nonce( 'plugin-name' ),
		'ajaxurl'      => admin_url( 'admin-ajax.php' ),
		'errorMsg'     => __( 'An error occurred', 'plugin-name' ),
	)
);
```
No escaping needed, WP will escape this.

### Arbitrary variable within javascript block
```php
<script type="text/javascript">
    var myVar = <?php echo $my_var; ?>
</script>
```
`$my_var` should be escaped with `esc_js()`.

### Arbitrary variable within inline javascript
```php
<a href="#" onclick="do_something(<?php echo $var; ?>); return false;">
```
`$var` should be escaped with `esc_js()`.

### Arbitrary variable within HTML attribute for use by javascript
```php
<a href="#" data-json="<?php echo $var; ?>">
```
`$var` should be escaped with `esc_js()`, `json_encode()` or `wp_json_encode()`.

:point_right:  **Is this correct ?**

### Arbitrary string within HTML textarea

```php
echo '<textarea>', $data, '</textareav>';
```
`$data` should be escaped with `esc_textarea()`.

### Arbitrary string within HTML tags

```php
echo '<div>', $phrase, '</div>';
```
This depends on whether `$phrase` is expected to contain HTML or not.
* If not, use `esc_html()` or any of its variants.
* If HTML is expected, use `wp_kses_post()`, `wp_kses_allowed_html()` or `wp_kses()` with a set of HTML tags you want to allow.

### Arbitrary string within XML or XSL context

```php
echo '<loc>', $var, '</loc>';
```

Escape with `ent2ncr()`

:point_right: **Is this correct ? and is this sufficient ?**

### Related references:
* https://developer.wordpress.org/plugins/security/securing-output/
* https://developer.wordpress.org/plugins/internationalization/security/
* https://developer.wordpress.org/themes/theme-security/data-sanitization-escaping/
* https://codex.wordpress.org/Data_Validation

:point_right: **Am I forgetting typical (even if rare) situations ? Does this cover everything and does this cover it correctly ?**

**Comment by dingo-d** [comment]
There is a minor typo if I'm not mistaken:

```php
echo '<a href="', $url, '">';
```

Should be 

```php
echo '<a href="' . $url . '">';
```

(commas should be dots), no?

Also I'd add for '_Arbitrary variable within HTML attribute for use by javascript_' that if you put html converted to json in the `data` attribute that  it's necessary to use `htmlentities()` like

```php
<a href="#" data-json="<?php echo htmlentities( wp_json_encode( $var ), ENT_QUOTES, 'UTF-8' ); ?>">
``` 

because of quotes.

**Comment by GaryJones** [comment]
Commas with `echo` are valid and slightly more performant memory-wise than concatenation.

**Comment by jrfnl** [comment]
@dingo-d What @GaryJones said about the comma's and it isn't even slightly more performant, but significantly more performant memory-wise. The memory usage of concatenation is exponential, so the more `.`s, the more memory will be used.

> Also I'd add for 'Arbitrary variable within HTML attribute for use by javascript' that if you put html converted to json in the data attribute that it's necessary to use `htmlentities()` like <snip> because of quotes.

Is there a specific reason to use `htmlentities()` instead of `esc_attr()` ?
Should the advise maybe be to always use `esc_attr()` when passing json encoded variables into an HTML attribute ?

**Comment by dingo-d** [comment]
Wow, wasn't aware of the comma 'concatenation' 😱  So I should use them everywhere where I use `echo`? 
I need to find a book with tips and tricks for php 😄 

@jrfnl When using `wp_json_encode()` in data attributes, if the data attribute is HTML (has "), the resulting json is often broken (which can cause the entire page to brake). Wrapping it `htmlentities()` will prevent this. And I think that `esc_attr()` is overly aggressive as a general use as well. I think that for data attributes it depends on what is placed as a data attribute. I rarely apply the same escaping functions in every case - sometimes I can place post id's, sometimes I can place json inside, or HTML that I'd like to use with JS, sometimes a simple string. So escaping of that attribute can vary (at least for me).

Plus, from what I've read in the manual `ENT_QUOTES` helps with XSS prevention (to some extent).

**Comment by jrfnl** [comment]
> Wow, wasn't aware of the comma 'concatenation' :scream: So I should use them everywhere where I use echo?
I need to find a book with tips and tricks for php

@dingo-d You may find the following two references useful in that case:
* [ClearPHP](https://github.com/dseguy/clearPHP/blob/master/rules/README.md)
* [PHP The right way](http://www.phptherightway.com/)

> I rarely apply the same escaping functions in every case - sometimes I can place post id's, sometimes I can place json inside, or HTML that I'd like to use with JS, sometimes a simple string. So escaping of that attribute can vary (at least for me).

Thanks for your input!

**Comment by JDGrimes** [comment]
> ### Arbitrary variable within javascript block
>```php
><script type="text/javascript">
>    var myVar = <?php echo $my_var; ?>
></script>
>```
> `$my_var` should be escaped with `esc_js()`.

`wp_json_encode()` should be used, rather than `esc_js()`. Better yet, don't do this and instead use `wp_localize_script()`.

If you must use `esc_js()`, remember that the value *must* be placed within single quotes. You're example us vulnerable to script injection. Try `$my_var = '1;alert(document.cookie)'`.

> ### Arbitrary variable within inline javascript
> ```php
> <a href="#" onclick="do_something(<?php echo $var; ?>); return false;">
> ```
> `$var` should be escaped with `esc_js()`.

Once again, this is vulnerable. You need single  quotes around the value. This is the one place where `esc_js()` is intended to be used though. But I'd still prefer `wp_json_encode()` and `esc_attr()`. Better yet, don't use inline scripts like this.

> ### Arbitrary variable within HTML attribute for use by javascript
> ```php
> <a href="#" data-json="<?php echo $var; ?>">
> ```
> `$var` should be escaped with `esc_js()`, `json_encode()` or `wp_json_encode()`.
> 
> :point_right:  **Is this correct ?**

`esc_js()` does little for you here, other than providing attribute escaping. I'd use `wp_json_encode()`, along with `esc_attr()`. Really though, unless this is specifically supposed to be a JSON encoded object (i.e., not a scalar value), I'd just escape it the same as I would normally escape an attribute (`(int)`, `esc_attr()`, etc.). The only reason you would need more than that is if you were `eval`ing it in some way, which you aren't. (Right?)

>### Arbitrary string within XML or XSL context

I honestly have no idea.

>👉 Am I forgetting typical (even if rare) situations ? Does this cover everything and does this cover it correctly ?

One thing I came across recently is escaping CSS. Not as big a deal as JS, but it is the other XSS (Cross-Site Styling) (and can lead to JS execution, at least on some legacy systems). Users aren't really allowed to use arbitrary styles in WP (unless they have the `unfiltered_html` cap), so you need to consider that when outputting a value within a `<style>` block or `style` attribute. Really, you shouldn't do this to begin with, but if you need to, I think there is a `safecss_filter_attr()` function, though I'm not entirely sure how it would be used. 

Inline scripts and styles should be discouraged in general anyway, IMO, in the hope that one day WP sites will be able to use a CSP without `unsafe-inline unsafe-eval`. (I can dream, can't I?)

I haven't thought of any other common cases off of the top of my head.

**Comment by dingo-d** [comment]
Can a check be made whether you've used correct escaping function? For instance it would warn you that you've used `esc_html()` where you should have used `esc_attr()`?

```php
<div class="<?php echo esc_html( $some_class_name ); ?>"> // Would throw a warning that you should use esc_attr() since class is an attribute.
```

**Comment by jrfnl** [comment]
@dingo-d There's an issue open about that #527. I made a very small preliminary start at some point, but never got round to finishing it.

**Comment by Ninetheme** [comment]
function myfunc() {
$output ='$variable';  //  -------------------  do we need to use it here?
// or
$output ='<a>$variable</a>';   -------------------  do we need to use it here?
return $output;
}

Do we need to use it in function ?  @jrfnl

**Comment by jrfnl** [comment]
@Ninetheme Your question is unclear.

1. Your function is not actually outputting any data - just returning -, so (late) escaping is not relevant.
2. The data your are passing to `$output` are single quoted strings, so the variable in it won't be evaluated, so again, escaping is not relevant.

**Comment by Ninetheme** [comment]
So do we need must use on esc_ in any function variable ? Are they different echo and return? I didn't found any article about escaping properly, thank you!

function myfunc() {
$output ='background:'.$variable.';  //  -------------------  do we need to use esc_attr here?
  wp_add_inline_style( 'crypterium-custom-style', $output );
}

@jrfnl

**Comment by dingo-d** [comment]
Since you are using `wp_add_inline_style` that means that `myfunc()` function will be used in a `wp_enqueue_scripts` hook as a callback function. In this case it would be good to escape the variable  `$variable`. Since escaping the whole `$output` could mess with the inline styles (as pointed out [here](https://codex.wordpress.org/Function_Reference/wp_add_inline_style)).

As for the general question, there are a lot of resources online where you can see the examples about escaping and sanitization:

https://developer.wordpress.org/themes/theme-security/data-sanitization-escaping
https://codex.wordpress.org/Validating_Sanitizing_and_Escaping_User_Data
https://vip.wordpress.com/documentation/validating-sanitizing-escaping

Hope these help.

**Comment by jrfnl** [comment]
Marking turning this thread into a wiki page about how to escape output as a `good first issue` for anyone who wants to contribute to WPCS.

**Comment by dorkster100** [comment]
I have a question regarding this:

> If HTML is expected, use wp_kses_post(), wp_kses_allowed_html() or wp_kses() with a set of HTML tags you want to allow.

But from: https://codex.wordpress.org/Data_Validation

> Note that the kses system can be resource-intensive, and should therefore not be run as an output sanitization filter directly, but as a filter to data after it has been input and processed, before it is saved in the database. WordPress runs kses on the pre_comment_content filter, for example, to filter the HTML before saving the comment.

So WP documentation actually suggests not to do that? So how do i properly escape html content for display?

**Comment by ramdhanishivam** [comment]
Which function should I use under this case(instead of using _e) ? 
_e( 'Start Date <span class=" ">(dd-mm-yyyy)</span>', ' ' );
Expected Output : Start Date (dd-mm-yyyy)

**Comment by jrfnl** [comment]
@zzap Just checking - could someone of the documentation team take a look at this issue and update whatever documentation pages would need updating for it ?

More than anything, this is a documentation issue about output escaping and not something which needs changes in WPCS, so we'd like to close this.

**Comment by zzap** [comment]
I opened docs issue for this and will work on it: https://github.com/WordPress/Documentation-Issue-Tracker/issues/635

You can close this one @jrfnl :raised_hands:

**Comment by jrfnl** [comment]
Thanks @zzap ! I look forward to seeing the result. Please feel free to approach us with any questions you run into.

**Comment by jrfnl** [comment]
One note in addition to the above discussion - the `esc_xml()` function was introduced in WP 5.5.0, so that can now be used for data which needs to go into an XML document.
