### ISSUE TITLE
Add an exception?

### ISSUE THREAD

**Issue by vladlu** [WordPress/WordPress-Coding-Standards#1775]
I'm very sorry if my issue looks bad (I feel it does). But here is a self-explanatory image of what I want:

![click this babe (imgur)](https://i.imgur.com/CkiEEwY.png)

I'm using the latest WordPress-Coding-Standards/Wordpress
 as a rules for PHP_CodeSniffer.

And phpcs (PHP_CodeSniffer)  wants to make my code look ugly. I want you to teach him not to want to do that. Thanks.

**Comment by jrfnl** [comment]
Sorry, but that code just doesn't comply with WPCS.

You can choose to wrap the code with whitelist comments for that specific error, but we'll not be making any changes to WPCS to allow this.

```php
// phpcs:disable Standard.Category.SniffName.ErrorCode
... your code ...
// phpcs:enable 
```

And as you provided a screenshot instead of a code sample, I can not tell you which error code to whitelist. Run `phpcs` with the `-s` option to find out for yourself.
