### ISSUE TITLE
Should sirbrillig/phpcs-no-get-current-user be included here?

### ISSUE THREAD

**Issue by yansern** [WordPress/WordPress-Coding-Standards#1973]
## Rationale

Was just wondering if `sirbrillig/phpcs-no-get-current-user` should be included here?

## References

https://github.com/sirbrillig/phpcs-no-get-current-user

**Comment by jrfnl** [comment]
I've had a quick look.

### Context

To provide a little more information as the issue doesn't explain anything:

* [`get_current_user()`](https://www.php.net/manual/en/function.get-current-user.php) is a PHP native function which retrieves the owner of the currently run PHP script.
* [`wp_get_current_user()`](https://developer.wordpress.org/reference/functions/wp_get_current_user/) is a WP native function which retrieves the current `WP_User` object.

So, it's easy enough to understand how people could confuse the two.

Additionally, some hosts use `disable_functions` to disable the PHP `get_current_user()` function for security reasons as can be [seen by the numerous support requests](https://wordpress.org/search/get_current_user()+has+been+disabled) about this.

### Should the sniff be included ?

Now, to answer the question asked by the op:
I don't think we should not include the sniff from `sirbrillig/phpcs-no-get-current-user` as we already have the logic in place in WPCS to handle detection of this kind of thing within WPCS, so there is no need to use an external library for this.

### Should calls to `get_current_user()` be detected ?

I seriously wonder how often the functions are being confused in reality, as the returned value is very different (object vs string) and approaching the string from `get_current_user()` as if it were a `WP_User` object should give enough errors during development to alert a developer to the fact that they are using the wrong function.

I think to answer that question, some research is needed via the theme and plugin directory to get some idea of:
1. How often the `get_current_user()` function is actually used in WP extensions.
2. Whether it is used correctly (calling the PHP function was the intention) or incorrectly.
3. Whether or not the use of the function is safeguarded against the function potentially being disabled.

If the overwhelming majority of the instances of `get_current_user()` calls found would be _false positives_, i.e. intentional use of the PHP native function, WPCS should **not** add a check for the function as it will only cause irritation.

However, if the overwhelming majority of the instances of `get_current_user()` calls found would be in the "dev confusion" category, it is warranted to add detection of the use of the function to WPCS.

Similarly, if the overwhelming majority of the (correctly called) instances of `get_current_user()` calls found would not have proper safeguards against the function potentially being disabled, again, a case could be made for detection being added to WPCS.

So, first point of action would be doing the research and reporting back with the aggregate results. Until there is more insight into whether this actually addresses a real problem, this should not be addressed in WPCS.

**Comment by yansern** [comment]
Thanks! This is very well articulated! Now I understand the realm of where WPCS is used and the factors to consider when implementing sniffing rules!  I guess I should close this issue? :)

**Comment by jrfnl** [comment]
> I guess I should close this issue?

@yansern Well, as I say above, if someone would do the research and the conclusion would be that the function is regularly used incorrectly ("dev confusion"), then it would be perfectly fine for WPCS to address this. But only then.

Until that research has been done, there's not much we can do within WPCS.

**Comment by dingo-d** [comment]
I did a quick search on the wpdirectory for 

`\b(get_current_user\()`

And got this for plugins:

https://wpdirectory.net/search/01EXMNB9549SGGEBT8TY7GZ8XV (1308 matches)

But from a quick inspection, those all seem to be correct uses of the `get_current_user()` function.

In themes, there are 25 matches

https://wpdirectory.net/search/01EXMNH6QF5HEFVWNJ682CKKSZ

But all of them seem to be coming from the logging script in the `freemius/includes/class-fs-logger.php` file. So, again, seems like a legitimate use case.

You can scour a bit more @yansern and see if there are any misuses of that function.

**Comment by apermo** [comment]
I know, it's an old topic, and closed, but I have some insights to be added.

I completely second the research, that developers will not publish code with mistaken `wp_get_current_user()`vs `get_current_user()` but as @jrfnl already mentioned, even while the return value is different, I have witnessed the mixup first hand in my team. And even though we found it, it wasn't straightforward. 
So I could perfectly imagine a sniff for Extra that would have the Message "Did you mean to use wp_get_current_user()" if someone uses `get_current_user()`.

It has the potential of reducing headache.

And the mixup is even easier, since [get_current_user_id()](https://developer.wordpress.org/reference/functions/get_current_user_id/) is a WordPress function. I would like a second thought on this one.

**Comment by jrfnl** [comment]
@apermo I still don't think a sniff is warranted.

Things flagged by a sniff should be actionable/solvable and an error/warning like "Did you mean to use wp_get_current_user()", is not actionable for valid uses of `get_current_user()`. The only thing which could be done is to add an ignore comment and that is not an acceptable premise for a sniff.

**Comment by apermo** [comment]
Thank you for the answer.
