### ISSUE TITLE
Autoloading using Composer, wpcs asks to append `class-` for the file name

### ISSUE THREAD

**Issue by laranz** [WordPress/WordPress-Coding-Standards#1975]
## Is your feature request related to a problem?
Autoloading using Composer, wpcs asks to append `class-` for the file name, but autoloading asks for file name as classname.

is there a solution for this?

**Comment by jrfnl** [comment]
Yes: use a `classmap` for the autoloading.

**Comment by laranz** [comment]
@jrfnl so, we need to add all the classes manually in the composer.json file? Is there any automatic way?

**Comment by jrfnl** [comment]
A `classmap` is automatically generated by Composer: https://getcomposer.org/doc/04-schema.md#classmap

**Comment by laranz** [comment]
### Composer way.
Classname.php

> Class Classname{
> ....
> }

### WordPress way.
class-classname.php

```
Class Classname{
....
}
```

Do you know how I add the `classmap` for the WordPress way? I can use the wildcards, but how to do the lowercase?

**Comment by jrfnl** [comment]
@laranz Sorry, but this is not a help forum for understanding Composer. I will try to help you one last time, but if you need more help after that, I suggest reading the Composer documentation or asking in a Composer oriented forum.

Given that you've not provided any information on your directory structure, I'm just going to presume it is something like:
```
| - project root
    | - scr
        | - plugin-file.php
        | - class-file.php
        | ... etc
```

You would add something like this to your `composer.json` file in the project root:
```json
{
    "autoload": {
        "classmap": ["src/"]
    }
}
```

Run `composer dump-autoload` from the command line (from the project root).

And add this to your plugin bootstrap file (path may need adjusting based on your actual directory structure):
```php
require_once dirname( __DIR__ ) . '/vendor/autoload.php';
```

Note: If your plugin has external dependencies and you intend to distribute it, please consider prefixing the external dependencies to prevent conflicts with other plugins which may use the same external dependencies. Have a look at [PHP-Scoper](https://github.com/humbug/php-scoper) if you need to handle that use-case.

**Comment by jrfnl** [comment]
@laranz One can still comment on a closed issue. Please DO NOT SEND ME EMAIL ABOUT THIS (ever again).

**Comment by laranz** [comment]
@jrfnl Sorry about that. 

Thanks for your help. 🎉

**Comment by jrfnl** [comment]
> Using the proposed `classmap` doesn't dynamically autoload based on namespaces, so **every** time you add a new class, you'll need to regenerate the autoload files with `composer dump-autoload`.

Correct and yes, I agree this can be annoying as a developer.

> In my case, the adaptation here is to ignore the WPCS ruleset

I hope you are only ignoring this one rule though ?

> PS: I have no idea if the static autoloader has a performance impact - probably not. 

It does, in a positive way. Using an authoritative class map is the fastest type of autoloading available via Composer.

**Comment by dingo-d** [comment]
You could try to see if you could utilise https://github.com/iqomp/watcher somehow, to run `composer dump-autoload` whenever a class is added. That would improve on the DX side of things.

As far as the performance goes with autoloading, there are [some cases](https://patrickallaert.blogspot.com/2013/03/benchmarking-composer-autoloading.html) (although it should be taken with a huge grain of salt since it's 10 years old), that will show that classmap autoloading may not be all that faster. It should be noted that PHP has grown a lot in these past 10 years, so I'd like to see some new benchmarking being done on newer PHP versions (especially PHP8 with JIT compiler, things like preloading (PHP 7.4), etc.).

In the end I think you can use PSR-4 in your projects (I opt for that in my pojects) and just generating classmap in the production builds. You get the best of both worlds.

I'd really like to see some benchmarks to see the impact on memory and loading time on real applications. Just to see if it's in the realm of micro-optimizations or not.

**Comment by smileBeda** [comment]
I did a quick test which is in no way fully covering the requirements of such tests, but I think it shows what "wins" (although IMO it is a negligible difference)

**Approach:**
1. Generated 1000 Classes (each in a file) with each one constructor and one property using a python script.
2. Loaded said classes using `psr4` in a brand-new WP Install using PHP8
3. Loaded said classes using `classmap` in the same install
4. Repeated the same in PHP 7 because `Your server is running PHP version 5.6.40 but WordPress 6.3.1 requires at least 7.0.0.`
The time was measured by using this code:
```
$start_time = microtime(true);
require 'vendor/autoload.php';
require 'loadall.php';// This file instantiates all classes from the `classes` folder (the 1000 thousand classes) in a  foreach loop.
$end_time = microtime(true);
var_dump( $end_time - $start_time);
die();
``` 

**Results**
|PHP8.2  | psr4                 | classmap             |
|-------|----------------------|----------------------|
| Row 1 | 0.0012960433959960938 | 0.005463123321533203|
| Row 2 |0.001016855239868164| 0.002830982208251953 |
| Row 3 |0.001300811767578125| 0.0034821033477783203|
| Row 4 |0.0014739036560058594| 0.003450155258178711 |
| Row 5 | 0.001252889633178711|0.003654003143310547|
| Row 6 | 0.001374959945678711 | 0.003632068634033203|

|PHP7.6   | psr4               | classmap           |
|-------|--------------------|--------------------|
| Row 1 | 0.0016272068023682 | 0.0032889842987061 |
| Row 2 | 0.001939058303833 | 0.0046589374542236|
| Row 3 | 0.0012898445129395 | 0.0029060840606689 |
| Row 4 | 0.001366138458252 |0.0028800964355469 |
| Row 5 | 0.001215934753418| 0.0029499530792236 |
| Row 6 | 0.0012521743774414| 0.0029170513153076|

I am surprised at these results, it appears the PSR4 is _always_ a bit faster, and what's even more surprising, is that the PHP7 seems faster at least with classmap compared to PHP8

Of course - this is A) no real world scenario, B) the classmap might be slower here since the file autoload size grew, and C), it is not a benchmark made with pro tools, but at least on a controlled, local install.

If this can be trusted, classmap is approx 50% slower compared to PSR4, at least, with that many (useless) classes.

As said, I think that difference is totally negligible - considering it loads 1000 classes in less than 5/1000st of a second in the slowest run ... I think it won't matter 

Would love some other input on this, although here might not be the right place.

**Comment by dingo-d** [comment]
Yeah, syntactic tests are always a bit... unreliable imo. I'd rather see how it would fare in real applications (some small symfony/laravel app for instance) with enough classes, dependency injections, etc., and benchmarking done using tools like [phpbench](https://github.com/phpbench/phpbench) or with [xhprof](https://www.php.net/manual/en/book.xhprof.php).

In your case the optimisation is really negligible imo (a definition of micro-optimisation).
