### ISSUE TITLE
Review the core ruleset against the WP handbook

### ISSUE THREAD

**Issue by dingo-d** [WordPress/WordPress-Coding-Standards#2064]
Before we release the WPCS 3.0 we should do a review of the [WordPress-Core ruleset](https://github.com/WordPress/WordPress-Coding-Standards/blob/develop/WordPress-Core/ruleset.xml).

We should check the sniffs (if any need to be removed/added or reorganized) and take into account the development of the [restructuring handbook sections](https://github.com/WordPress/wpcs-docs/issues/93) issue - once we come to a consensus reorganize everything to match the handbook sections as well.

**Comment by jrfnl** [comment]
Just thinking: quite a lot of the sniffs also contain links to the handbook in the docblock, but those links are outdated since the standards have moved to their own handbook and will be even more outdated once the standards have been updated.

I suggest we also do a codebase wide search for handbook links and verify and update all of these.

**Comment by jrfnl** [comment]
Re-opening as this part still needs addressing (and we may also want to do a final cross-check of the handbook vs the Core ruleset just before release as between now and then more changes are expected).

> I suggest we also do a codebase wide search for handbook links and verify and update all of these.
