### ISSUE TITLE
MariaDB generating error when we are using %s as placeholder for table name when CS(code sniffer) suggest to used %s instead %i

### ISSUE THREAD

**Issue by crathod-io** [WordPress/WordPress-Coding-Standards#2434]
**ERROR WordPress.DB.PreparedSQLPlaceholders.UnsupportedIdentifierPlaceholder**

The %i modifier is only supported in WP 6.2 or higher. Found: "%i".

**Comment by swissspidy** [comment]
Since you came here [from WordPress Trac](https://core.trac.wordpress.org/ticket/60813), I am repeating my questions here:

Where is this error being reported? In WordPress core?

If not, you should report such things to the affected plugin or theme. If this happens in your own project, the error message is pretty self-explanatory. "%i" is only supported on WP 6.2+, so if you support older versions you need to fall back to something else.

**Comment by crathod-io** [comment]
@swissspidy apologies in this repo or plugin: https://github.com/WordPress/plugin-check/

**Comment by crathod-io** [comment]
@swissspidy I'm going to close this ticket.
