### ISSUE TITLE
NoSpacesAroundArrayKeys doesn't like dynamic strings

### ISSUE THREAD

**Issue by Rarst** [WordPress/WordPress-Coding-Standards#404]
`$events["{$prefix}_before_header"]` triggers an error about needing spaces around string, while technically it is _still_ a string overall and doesn't need spaces around, as per letter of the standards.

**Comment by GaryJones** [comment]
The Handbook doesn't really cover this, but due to dynamically-named filters, there should be plenty of examples in core. Do they have a consistent approach?

**Comment by Rarst** [comment]
From quick search core doesn't have spaces around dynamic string array keys.

**Comment by JDGrimes** [comment]
I favor at least adding the option to disable flagging interpolated strings. I also find it more natural to write `$array["{$dynamic}_key"]` than `$array[ "{$dynamic}_key" ]`.  The spaces seem unnecessary in this case.

**Comment by jrfnl** [comment]
We've just checked and it looks like this has been enforced since the introduction of the sniff in `0.3.0`, i.e. `$a["test"]` is fine without spaces, `$a[ "$interpolated-test" ]` needs spaces.

Changing this now would be a BC break AND cause a lot of code churn.

Adding an option to specify the preference for spacing around interpolated strings would not be a BC break, but other than this issue, I've not seen any comments to that effect anywhere else, so I don't get the impression there is much call for this.

I'm going to close this issue as `wont fix`, but am open to re-opening it specifically for adding the option (not for changing the default behaviour) if there is more support for adding this option.
