### ISSUE TITLE
PHPCBF only partially fixes spacing in this block

### ISSUE THREAD

**Issue by paulschreiber** [WordPress/WordPress-Coding-Standards#438]
With `phpcbf --standard=WordPress-VIP test.php`, spaces are added to the inner function, but not to `usort()`.

Before:

``` php
<?php
usort($authors, function ($a, $b) {
    $a = 1;
});
?>
```

After:

``` php
<?php
usort($authors, function ( $a, $b ) {
    $a = 1;
});
?>
```

Expected:

``` php
<?php
usort( $authors, function ( $a, $b ) { // space after usort(
    $a = 1;
}); // maybe here too
?>
```

**Comment by JDGrimes** [comment]
We use `PEAR.Functions.FunctionCallSignature` from upstream in PHPCS to sniff for function call spacing. PEAR standards require special spacing for multi-line function calls, and because this doesn't match WordPress's standards, [we disable those parts of the multi-line function call checks in our ruleset](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/develop/WordPress-Core/ruleset.xml#L68-L73). I think we need to subclass that sniff and override the method that handles multi-line function calls.

**Comment by jrfnl** [comment]
PR https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/1020 made a change to how this is handled in the fixer.

The snippet would now be fixed as:
```php
usort(
	$authors, function ( $a, $b ) {
		$a = 1;
	}
);
```

@paulschreiber Considering the above, can this issue be closed ?

**Comment by paulschreiber** [comment]
That seems like too much space. Putting `$authors` on its own line makes it harder to track that it's a parameter to `usort()`. I prefer the solution in "Expected" above.

**Comment by jrfnl** [comment]
Currently, the snippet would be fixed to:
```php
usort(
	$authors,
	function ( $a, $b ) {
		$a = 1;
	}
);
```

While we can have opinions on whether this is too much space or not, it is not incorrect as a fix, so I'm going to close this issue as superseded by a changed reality.
