### ISSUE TITLE
'Expected next thing to be escaping function, found "!"' in ternary condition

### ISSUE THREAD

**Issue by dingo-d** [WordPress/WordPress-Coding-Standards#677]
I need a bit of clarification on this one. I have, in my theme, an input field for a breadcrumbs title that I can set in my page metabox, and I am outputting it like this

```
<?php echo ( ! empty( $my_bc_title ) ) ? wp_kses( $my_bc_title, allowed_tags() ) : get_the_title(); ?>
```

The `allowed_tags()` is just a function with allowed tags array. Now, the issue is probably in the fact that after `echo` everything should be sanitized, but I'm just checking if the variable is empty, and then basically sanitize it with `wp_kses()`, and `get_the_title()` function should be safe. 

Also what If I sanitize it beforehand with `esc_html()`, when pulling it out of post custom field?

Should I ignore these kind of errors or?

**Comment by JDGrimes** [comment]
Can you post the actual error that you are getting? I'm not sure why this would be flagged for sanitization, since it is generating output, not working with direct user input. Any error would be about *escaping*, I'd expect, not sanitization. 



> Also what If I sanitize it beforehand with esc_html(), when pulling it out of post custom field?

And what if you didn't? Just by looking at that line of code, there is no way to know. The sniff is based on the principle of late escaping, which means that you escape the value just before you use it. That way there is never any question about whether the value is safe or not. A developer can look at the code and see at a glance that the value has been escaped, and automated tools like WPCS can also see this more easily as well.



> Should I ignore these kind of errors or?

No. But if you don't understand why a particular line of code is getting flagged, you are right to ask us about it, because maybe it is a bug. :-)

**Comment by dingo-d** [comment]
The error I got was 

`Expected next thing to be an escaping function (see Codex for 'Data Validation')`

Isn't escaping a form of sanitization? That's why I put that in the title, could have been more clearer, sorry.

You do have a point tho. The thing that is kinda confusing is that every time I use `echo` and I don't have an escaping function (or a WordPress safe function) I get an error. This will throw the same error:

```
<?php echo ( ! empty( esc_html( $my_bc_title ) ) ) ? wp_kses( $my_bc_title, allowed_tags() ) : get_the_title(); ?>
```
I'm using a ternary operator to check my variable. This is a valid code, but still gives the error, and it's absolutely safe (right?).

Does that mean that it's a bad coding practice to do this?

Thanks for the clarification.

**Comment by JDGrimes** [comment]
> The error I got was
> 
> Expected next thing to be an escaping function (see Codex for 'Data Validation')

I would expect the error to indicate what it found that wasn't an escaping function. Like "found [something]". Is that the whole error? Maybe you aren't using the latest version of WPCS.


> Isn't escaping a form of sanitization? That's why I put that in the title, could have been more clearer, sorry.

Well, yes and no. WPCS general makes a distinction between the two: santization is performed on input data, escaping is perform on output. 

> I'm using a ternary operator to check my variable. This is a valid code, but still gives the error, and it's absolutely safe (right?).

WPCS is smart enough to know that the conditional part of the ternary doesn't need to be escaped, so it shouldn't flag anything before the `?`. (And so there is no need for you to use `esc_html()` in the `empty()` check. That will actually cause errors on older versions of PHP.)

I'm assuming that maybe the issue is that `allowed_tags()` is being flagged, and if so, that is a bug. The second argument of `wp_keses()` should likely be entirely ignored by WPCS.

**Comment by GaryJones** [comment]
If the ternary is split into a more traditional `if/else`, does the warning still happen? If so, which part does it reference?

**Comment by dingo-d** [comment]
When I split the ternary in the traditional `if/else` the `!` gets singled out and the same error appears

```
Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '!'
```

When I'm in ternary, the variable inside the `empty()` function gets marked, but the same error as the above happens, and also the `allowed_tags()` function gets marked saying the same error, but with `not 'allowed_tags'` part.

I originally did this on my work computer, but today I installed it at my home computer and same thing happens.

The CodeSniffer version is 2.6.2

```
PHP_CodeSniffer version 2.6.2 (stable) by Squiz (http://www.squiz.net)
```

And the WPCS version is the latest one `## [0.10.0] - 2016-08-29`

**Comment by stuartshields** [comment]
@JDGrimes Let me know if this is the correct place to talk about the sanitzation issues.

I'm noticing a return on:
```wpautop( get_the_author_meta( 'description' ) )```

Error msg:
```
Expected next thing to be an escaping function (see Codex for 'Data Validation'), not 'wpautop' (WordPress.XSS.EscapeOutput.OutputNotEscaped)
```

Is the above error correct in this instance?

**Comment by westonruter** [comment]
@stuartshields the escaping function needs to be the outer-most one. Late escaping is the best practice here. If you want to retain the paragraph tags, then use `wp_kses_post()`.

**Comment by stuartshields** [comment]
@westonruter Thanks for the heads up :)

**Comment by JDGrimes** [comment]
I can still reproduce the issue with this code:

```
<?php echo ( ! empty( $my_bc_title ) ) ? wp_kses( $my_bc_title, allowed_tags() ) : get_the_title(); ?>
```

So this appears to be a bug that could still be addressed.

Note that removing the parentheses around the ternary conditional makes the error go away:


```
<?php echo ! empty( $my_bc_title ) ? wp_kses( $my_bc_title, allowed_tags() ) : get_the_title(); ?>
```

**Comment by killua99** [comment]
I'm running with the same error using this code

```
<p><?php esc_html_e( $my_bc_title, 'my-plugin-settings' ); ?></p>
```

Having this error message:

```
Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$my_bc_title' (WordPress.XSS.EscapeOutput.OutputNotEscaped)
```

What would be a good solution for this? This variable came from my options settings. I do need translation option here and wpml-config.xml help me to translate it. Now, how could I escape it? I did try all the white list available.

**Comment by jrfnl** [comment]
Another code example of ternary conditions not being recognized correctly in the `EscapeOutput` sniff:

```php
printf(
	'<li><a href="#%1$s" class="%2$s"%3$s%4$s>%5$s</a></li>',
	esc_attr( $this->name ),
	esc_attr( $this->link_class ),
	( '' !== $this->link_title ) ? ' title="' . esc_attr( $this->link_title ) . '"' : '',
	( '' !== $this->link_aria_label ) ? ' aria-label="' . esc_attr( $this->link_aria_label ) . '"' : '',
	esc_url( $this->link_content )
);
```

Interestingly, the sniff does not throw any errors for the _first_ ternary ( `$this->link_title` ), but **does** throw errors for the second ( `$this->link_aria_label` ).
