### ISSUE TITLE
Handbook clarifications

### ISSUE THREAD

**Issue by GaryJones** [WordPress/WordPress-Coding-Standards#692]
I've written up a [list of ambiguities](https://gist.github.com/GaryJones/303d8b9ebb2d6a5bb800) that I feel the WP CS Handbook page has, which I believe can be addressed by adding a few clarifications. Some are one-line clarifications which shouldn't be an issue to anyone, some would be new sections (namespaces, anyone?) which may need consensus (with who?!) but are still warranted.

@westonruter: as you're a core committer, and can also edit the handbook, please could you take a look through my list and add in the clarifications you feel comfortable doing?

For any others points, I'm open for discussion about the "hole" I've identified, and suggestions on how to get clarification / consensus among the core committers as needed (with the proviso that we know WP Core is historically poor, though improving, at following it's own standards, and that these are coding standards for the WordPress _community_.

For us here, I feel that having these clarified would potentially allow some of the `WordPress-Extras` to be in `WordPress-Core`, or otherwise remove any doubt that something ambiguous in the Handbook is misrepresented in `WordPress-Core` ruleset.

cc @johnbillion and @jorbin who I believe also have interests here.

**Comment by jrfnl** [comment]
> we know WP Core is historically poor, though improving

I'd say improving a lot - PHPCS is giving it an `A` for consistency ;-)

The report might actually be useful to identify additional "hidden" rules: https://squizlabs.github.io/PHP_CodeSniffer/analysis/WordPress/WordPress/index.html

**Comment by GaryJones** [comment]
> I'd say improving a lot - PHPCS is giving it an A for consistency ;-)

That means:

> 97.1% of the project's source code conforms to the same coding conventions

...which in turns means it's a consistent code base - not that it's consistent with the standards in the handbook!

**Comment by jrfnl** [comment]
True enough, but if you look in more detail, it largely is (on those things which are being measured).

**Comment by GaryJones** [comment]
https://github.com/GaryJones/PHP-Coding-Standards is what was started a while ago, with the aim to get the items from my gist, plus other clarifications from others.

It would be really great if a core committer would at least clarify whether this is the right approach to getting the contents of the Handbook improved.

**Comment by westonruter** [comment]
@GaryJones My concern with contributing to a GitHub repo is that it will be difficult to keep it in sync. For one, the Handbook version is HTML but your version is Markdown. 

If contribution via GitHub is desired, then I think it would be better if the latest version from WordPress.org were continually synced down via the REST API and then pull requests could be made on top of that version. Ideally the version stored in Git would be the `raw` post `content` to make it easier to just copy/paste the new content into the post editor. Nevertheless, it seems the handbook pages aren't currently exposed in the REST API under https://make.wordpress.org/core/wp-json/wp/v2

Maybe I am over-engineering things and it would be better to just propose changes via issues and describe how the changes should be made manually. It seems that commenting has been turned off on the handbook page, but that seems like it would have been a good way to report issues instead of doing it in a separate place. Maybe also this would be something that should be rather tracked in Meta Trac? Each handbook change could be opened as a separate Trac ticket for discussion.

**Comment by jrfnl** [comment]
@GaryJones I believe a lot of this has been addressed with the recent changes in the handbook and WPCS. Are you okay with closing this issue ?
