### ISSUE TITLE
XSS: Secure variable with hardcoded values

### ISSUE THREAD

**Issue by grappler** [WordPress/WordPress-Coding-Standards#748]
Split off from #744

Here are a few examples where it should be possible to work out if the data in the variable is safe.

```php
$categories_list = get_the_category_list( esc_html__( ', ', '_s' ) );
if ( $categories_list && _s_categorized_blog() ) {
	printf( '<span class="cat-links">' . esc_html__( 'Posted in %1$s', '_s' ) . '</span>', $categories_list ); // WPCS: XSS OK.
```

```php
function hamburger() {
	$hamburger = '';
	$hamburger .= 'hamburger';
	echo $hamburger;
}
```

Additionally there should be an error on the line where `get_template_directory_uri()` is used and not when it is being echoed.

```php
function hamburger() {
	$hamburger = '';
	$hamburger .= get_template_directory_uri();
	echo $hamburger;
}
```

**Comment by JDGrimes** [comment]
I originally replied in https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/744#issuecomment-269216758:

> Similar has been suggested before, but I'm not sure that it is entirely in the spirit of late escaping, and I have to wonder where do we draw the line? I believe that handling cases like this will just make the sniff more complex and less efficient, while introducing more possibilities of false positives.
> 
> This sniff's job is *not* to detect XSS. It is to detect when `echo` is not being escaped. These aren't false-positives, they are the way that the sniff was designed. If we want to allow these to be handled then we'll either need a different sniff or a flag that enables this more advanced checking.
> 
> Your [second] example is so simple that it is pretty obvious that escaping isn't needed. It is also unnecessarily verbose. It is 100 times simpler to refactor that so that no concatenation is used, than it is to refactor the sniff. :-)
> 
> The [first] example is more complex. So complex that I cannot tell at a glance whether the value needs to be escaped or not. *That is the point of this sniff, and of late escaping: you should always be able to tell without having to see any surrounding code that the output is safe.*
> 
> So, I think you are looking for a different sniff, perhaps.


@grappler's [response](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/744#issuecomment-269220111):

> > Similar has been suggested before, but I'm not sure that it is entirely in the spirit of late escaping, and I have to wonder where do we draw the line? I believe that handling cases like this will just make the sniff more complex and less efficient, while introducing more possibilities of false positives.
> 
> I agree that we should escape late but I would prefer to escape a specific piece of data instead of a whole HTML block before it is echoed.

I agree, and I think that maybe you misunderstand what I am saying. These two positions aren't mutually exclusive, they actually go hand-in-hand. Everything should be escaped as late as possible, *and* also, to make this simpler, they should be output as early as possible. These naturally go together.

There are of course reasons that it is sometimes hard to output early because of coding preferences or just the way that WordPress's APIs are designed. But I'm all for echoing and escaping each piece of data individually. But the echo and escaping need to go together.

> > This sniff's job is not to detect XSS. It is to detect when echo is not being escaped
> 
> If that is so that then the class name and folder structure do not illustrate that.

True. This sniff has been influenced by VIP's philosophy of using late escaping to prevent XSS. I wholeheartedly agree with that philosophy, but maybe we do need to differentiate between a late escaping sniff and an XSS sniff. Back-compat will be difficult though. And honestly, I don't think that PHPCS is the tool for detecting XSS. It is too geared toward code-style stuff to be a good general tool for static code analysis.
